% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Dec-2020 00:15:02
%  MATLAB version: 9.7.0.1216025 (R2019b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('nonstoch.mat');

EEE = saveVarsMat.EEE; % <1x1498 double> too many elements

kcross = saveVarsMat.kcross; % <2x5000 double> too many elements

kmts = saveVarsMat.kmts; % <1500x1 double> too many elements

clear saveVarsMat;
