% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Nov-2020 18:12:42
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
saveVarsMat = load('stoch.mat');

EEE = saveVarsMat.EEE; % <1x1498 double> too many elements

kcross = saveVarsMat.kcross; % <1x10000 double> too many elements

kmts = saveVarsMat.kmts; % <1500x1 double> too many elements

clear saveVarsMat;
